name: Auto Commit Changes

on:
  workflow_dispatch:
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure git
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Auto commit changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "Auto: Commit changes from workflow"
          git push origin main
